apiVersion: apps/v1
kind: Deployment
metadata:
  name: iptreatmentoffering-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: IPTreatmentOffering
  template:
    metadata:
      labels:
        app: IPTreatmentOffering
    spec:
      containers:
      - name: iptreatmentoffering1repos
        image: iptreatmentmanagement3cr.azurecr.io/iptreatmentoffering1repos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: iptreatmentofferingsn

---
apiVersion: v1
kind: Service
metadata:
  name: iptreatmentoffering
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: IPTreatmentOffering